services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    depends_on:
      - db
    env_file:
      - ./api/.env
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./api/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: